apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    service: beacon
  labels:
    l1.service: beacon
  name: beacon
spec:
  replicas: 1
  selector:
    matchLabels:
      l1.service: beacon
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        service: beacon
      labels:
        l1.service: beacon
    spec:
      containers:
        - name: beacon
          image:
            sigp/lighthouse:v7.0.0-beta.0
          command:
            - lighthouse
          args:
            - bn
            - --datadir
            - /data_beacon
            - --testnet-dir
            - /data/testnet-dir
            - --enable-private-discovery
            - --disable-peer-scoring
            - --staking
            - --enr-address
            - 127.0.0.1
            - --enr-udp-port
            - "9000"
            - --enr-tcp-port
            - "9000"
            - --enr-quic-port
            - "9100"
            - --port
            - "9000"
            - --quic-port
            - "9100"
            - --http
            - --http-port
            - "3500"
            - --http-address
            - 0.0.0.0
            - --http-allow-origin
            - '*'
            - --disable-packet-filter
            - --target-peers
            - "0"
            - --execution-endpoint
            - http://el:8551
            - --execution-jwt
            - /data/jwtsecret
            - --always-prepare-payload
            - --prepare-payload-lookahead
            - "8000"
            - --suggested-fee-recipient
            - 0x690B9A9E9aa1C9dB991C7721a92d351Db4FaC990
            - --builder
            - http://mev-boost:5555
            - --builder-fallback-epochs-since-finalization
            - "0"
            - --builder-fallback-disable-checks
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 1
            timeoutSeconds: 30
            exec:
              command:
                - chmod +x /artifacts/scripts/query.sh && /artifacts/scripts/query.sh http://localhost:3500/eth/v1/node/syncing
          ports:
            - containerPort: 9000
              protocol: UDP
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9100
              protocol: TCP
            - containerPort: 3500
              protocol: TCP
          volumeMounts:
            - mountPath: /data/jwtsecret
              name: beacon-jwtsecret
            - mountPath: /data/testnet-dir
              name: beacon-testnet
            - mountPath: /artifacts
              name: beacon-artifacts
            - mountPath: /data_beacon
              name: beacon-volume

      restartPolicy: Always
      volumes:
        - hostPath:
            path: /mnt/sceal/storage/jwtsecret
            type: File
          name: beacon-jwtsecret
        - hostPath:
            path: /mnt/sceal/storage/testnet
          name: beacon-testnet
        - hostPath:
            path: /mnt/sceal/storage
          name: beacon-artifacts
        - hostPath:
            path: /mnt/sceal/storage/volume-beacon-data
          name: beacon-volume
          