---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contender
  labels:
    app: contender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contender
  template:
    metadata:
      labels:
        app: contender
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - std-guest
      containers:
        - name: contender
          image: docker.io/cbarbieru/contender:0.5.5-cb-3
          command: ["/bin/sh", "-c"]
          args: ["sleep infinity"]
          volumeMounts:
            - name: contender-reports
              mountPath: /root/.contender/reports
            - name: scenarios-config
              mountPath: /data/scenarios
            - name: script-config
              mountPath: /script
            - name: jwt-secret
              mountPath: /data/jwtsecret
      volumes:
        - name: contender-reports
          hostPath:
            path: /tmp/builder-playground-opstack-k8s/contender/reports
        - name: scenarios-config
          hostPath:
            path: /tmp/builder-playground-opstack-k8s/contender/scenarios
        - name: script-config
          hostPath:
            path: /tmp/builder-playground-opstack-k8s/contender/script
        - name: jwt-secret
          hostPath:
            path: /tmp/builder-playground-opstack-k8s/storage/jwtsecret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foundry-test
  labels:
    app: foundry-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foundry-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: foundry-test
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - std-guest
      containers:
        - name: foundry-test
          image: ghcr.io/foundry-rs/foundry:latest
          command: ["/bin/sh", "-c"]
          args: ["sleep infinity"]
          env:
            - name: RPC_URL
              value: http://op-geth:8545
            - name: ADDR
              value: 0xEbFDBdc8Dc86220aad9C581E0Bd68391bC11e170
            - name: PRIV_KEY
              value: 0x6e618720a28574533d1abe73babd6b2a87095a1361ab18572d995ba9fd1629b5
      restartPolicy: Always
