apiVersion: v1
kind: ConfigMap
metadata:
  name: contender-scenario
data:
  stress.toml: |
    [[spam]]
    [spam.tx]
    to = "{_sender}"
    from_pool = "spammers"
    signature = "hey()"
    args = []
    value = "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contender-script
data:
  run.sh: |
    #!/bin/sh

    PREFUNDED_PRIV_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
    PREFUNDED_ADDRESS=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
    echo "Using prefunded address: $PREFUNDED_ADDRESS"

    echo "Running contender setup..."
    contender setup \
      -p $PREFUNDED_PRIV_KEY \
      /data/scenario/stress.toml \
      -r http://rollup-boost:8551 \
      --op

    echo "Running fill-block spam workload..."
    contender spam \
      --tps 50 -d 10 -l 1 \
      --min-balance 0.2eth \
      -p $PREFUNDED_PRIV_KEY \
      -r http://op-rbuilder:8545 \
      --op fill-block
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contender
  labels:
    app: contender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contender
  template:
    metadata:
      labels:
        app: contender
    spec:
      containers:
        - name: contender
          image: flashbots/contender:latest
          command: ["/bin/sh", "-c"]
          args: ["sleep infinity"]
          volumeMounts:
            - name: contender-data
              mountPath: /root/.contender
            - name: scenario-config
              mountPath: /data/scenario
            - name: script-config
              mountPath: /script
            - name: jwt-secret
              mountPath: /data/jwtsecret
      volumes:
        - name: contender-data
          emptyDir: {}
        - name: scenario-config
          configMap:
            name: contender-scenario
        - name: script-config
          configMap:
            name: contender-script
            defaultMode: 0755
        - name: jwt-secret
          hostPath:
              path: /mnt/sceal/storage/jwtsecret